### ISSUE TITLE
Issue Parsing Discovering Tests

### ISSUE THREAD

**Issue by CRasico** [Issafalcon/neotest-dotnet#39] opened 2023-01-04 23:59 UTC
First off love the addition of a .net test adapter to neotest, definitely one of my favorite plugins to use. 

I'm currently running into an issue in which the various test files are unable to be parsed. Taking a look at the debug log of neotest, I believe it may have to do with the way my treesitter is setup, although I do have the `c_sharp` parser installed for treesitter.

![image](https://user-images.githubusercontent.com/53454804/210672035-43ea1012-2bc6-4051-8d2a-02a11b5371f4.png)

Are there any other requirements surrounding the tree sitter configuration and parser setup that would lead to this issue?
[neotest.log](https://github.com/Issafalcon/neotest-dotnet/files/10348299/neotest.log)

**Comment by Issafalcon** [comment] 2023-01-05 17:47
Hi @CRasico ! Thanks! I'm pleased you find it useful! 

The logs suggest the issue is within neotest core, rather than this adapter, but you're right in that it points towards the treesitter parser.

If you run `checkhealth` in neovim, what does the treesitter parse check status show for c_sharp?

**Comment by CRasico** [comment] 2023-01-05 23:25
Yeah absolutely, to me it appears everything related to `nvim-treesitter` and `vim.treesitter` are returning completely healthy.  That said, although I don't believe I'm on an outdated version. Really appreciate your help with this @Issafalcon 

## Tree Sitter Parser Health
![image](https://user-images.githubusercontent.com/53454804/210898800-b9f10dff-5dda-445b-aeb6-7c862c6a3ce4.png)

## Nvim TreeSitter Parser 
![image](https://user-images.githubusercontent.com/53454804/210898872-1429d800-f0e3-4659-addf-91bde331ddc7.png)

**Comment by Issafalcon** [comment] 2023-01-17 07:50
Hi @CRasico . Sorry I've not had time to get back to you til now. I'm not sure what's happening tbh. Did you manage to get any further to solving it?

**Comment by CRasico** [comment] 2023-01-22 20:08
I've started digging into the internals of `neotest` to see if there was anything significant. I did notice that I have two location of parser install's, one being neovim's default parser location, and nvim-treesitters location. 

When running test the logfile is utilizing the default location of the parsers, which would never contain the `c_sharp` parser. I haven't made much progress since then trying to determine how I can change the parser install location currently so that all of my parsers are in the optimal location. 

Not sure if you've seen anything similar before?

**Comment by Issafalcon** [comment] 2023-01-22 20:47
I actually had this when I migrated from using Packer to using Lazy.nvim recently. https://github.com/nvim-treesitter/nvim-treesitter/issues/3092 was the best thing I found that helped me. I had to completely remove all treesitter parsers and then re-install tree-sitter and all the parsers by using `:TSInstall all`. Try following that guide and hopefully it will reset the parser location.

**Comment by Issafalcon** [comment] 2023-01-29 13:34
I'll close this as it isn't an issue with the adapter, but rather an issue with treesitter parsers in neovim

**Closed** 2023-01-29 13:33 UTC
